### ISSUE TITLE
rebase on upstream

### ISSUE THREAD

**Issue by ZachBacon** [libretro/vbam-libretro#43]
as the topic suggest, would it be possible to rebase on upstream https://github.com/visualboyadvance-m/visualboyadvance-m. This way we can bring things in sync much like nestopiaue?

**Comment by retro-wertz** [comment]
this should not be that hard, since this core only supports gba. i dont mind doing this but my PR are taking long to get noticed, even if theyre only a few lines(usually i only do PR when necessary like fixing bugs) of code.

**Comment by ZachBacon** [comment]
Well considering I'm the upstream author and project lead for vba-m, I honestly would prefer this work be brought back into the fold, easier maintenance all around for the retroarch crew and especially since we already merged in stuff before for libretro core code. Just a shame to see twinaphex maintain this old fork instead of working with us to get this folded in upstream.

**Comment by retro-wertz** [comment]
thats great to have an author visit here. you may want to tag @twinaphex regarding this issue...

on a related note, can you take a look at my last PR regarding input lag. this core and mainstream standalone vbam(using linux) using frameskip have an extra 1 frame of input lag. example, super mario advance 4 (play super mario 3) jumps on the 3rd frame instead of on the 2nd in some other gba emu or core. i just move input reading ahead of CPULoop and break loop when a frame is done.

**Comment by retro-wertz** [comment]
we are now upstreamed.... its just a matter of syncing both repo..

**Comment by hizzlekizzle** [comment]
Closing this issue, since the task is complete. Feel free to reopen if necessary.
