### ISSUE TITLE
Compiling fails when using clang

### ISSUE THREAD

**Issue by retro-wertz** [libretro/vbam-libretro#45]

**Comment by retro-wertz** [comment]
PR sent. should also silence warning when compiling with gcc

```
../gba/Cheats.cpp:2485:18: warning: narrowing conversion of ‘((value >> 8) & 255)’ from ‘u32’ {aka ‘unsigned int’} to ‘u8’ {aka ‘unsigned char’} inside { } [-Wnarrowing]
     (value >> 8) & 255,
     ~~~^~~
```

**Comment by retro-wertz** [comment]
NOT RESOLVED....

**Comment by retro-wertz** [comment]
PR ignored. no plan maintain i guess....

**Comment by hizzlekizzle** [comment]
I didn't merge it because I'm not very good at code review, but if Zachbacon wants us to drop our fork anyway, and we're not merging fixes, it seems like we may as well do so. I'll try to ask around about it.

**Comment by fr500** [comment]
@retro-wertz not sure what the problem is here, there's a lot of repos and some PRs just get lost in the noise, if you close it, it will never be noticed

for code review just tag @twinaphex I guess

as for rebasing, it could be desirable, but it's not like anyone can just go and rebase, afaik, the core diverges a lot from upstream, it may take a while to have it ready.

**Comment by ZachBacon** [comment]
To be honest, I kept as much as I could with this fork and kept asking twinaphex, got me almost no where
