### ISSUE TITLE
Regression: Sonic Advance & Sonic Advance 2 have grey boxes on startup

### ISSUE THREAD

**Issue by Metasynic** [libretro/vbam-libretro#52]
Expected behaviour: Sonic Advance and Sonic Advance 2 boot normally.
Actual behaviour: Both games load a screen with four grey boxes, play some music, and stay like that forever.

This happens on both Sonic Advance (U) and Sonic Advance 2 (U). I've tested them with the latest master on the main visualboyadvance-m repository and it's working fine over there, so it seems to have been fixed upstream already. This can easily be replicated by loading either of the ROMs.

My specs in case it matters: Ryzen 5 1500X, GTX 970, Ubuntu 18.04.

**Comment by retro-wertz** [comment]
Since libretro port does not official support Link modes, a bypass has been added so games that so games uses some serial io functions would still boot with needing the link-related functions(hence not adding unnecessary dependencies to core)

There was a missing write value during initializing causing Sonic Advance games to go into its somewhat multiplayer modes.

This should be corrected in PR.
